using UnityEngine;

public class BrotherBlueView : MonoBehaviour
{
    [SerializeField] private Animator animator;
    private static readonly int Sell = Animator.StringToHash("Sell");
    private static readonly int Open = Animator.StringToHash("Open");
    private static readonly int CleaningA = Animator.StringToHash("CleaningA");
    private static readonly int CleaningB = Animator.StringToHash("CleaningB");
    private static readonly int MoveSideways = Animator.StringToHash("MoveSideways");
    private static readonly int[] CloseTriggerArray = {CleaningA, CleaningB, MoveSideways};

    public void SellAction()
    {
        animator.SetTrigger(Sell);
    }

    public void OpenAction()
    {
        animator.SetTrigger(Open);
    }

    public void CloseAction()
    {
        animator.SetTrigger(CloseTriggerArray.RandomChoose());
    }
}
