using System;
using System.Collections.Generic;
using UnityEngine;

public class CustomerDirection : MonoBehaviour
{
    [SerializeField] private List<Transform> bodySides = new List<Transform>();

    public void SetDefaultSide()
    {
        foreach (var bodySide in bodySides)
        {
            bodySide.localRotation = Quaternion.Euler(Vector3.zero);
        }
    }
    
    public void SetFlipSide()
    {
        foreach (var bodySide in bodySides)
        {
            bodySide.localRotation = Quaternion.Euler(Vector3.up * 180);
        }
    }
}
