using System;
using UniRx;
using UnityEngine;
using UnityEngine.UI;

public class HeaderManager : MonoBehaviour
{
    [SerializeField] private Button settingButton;
    [SerializeField] private Button missionButton;
    [SerializeField] private Button informationButton;

    private void Start()
    {
        settingButton.OnClickAsObservable().ThrottleFirst(TimeSpan.FromSeconds(1f)).Subscribe(_ =>
        {
        });
        missionButton.OnClickAsObservable().ThrottleFirst(TimeSpan.FromSeconds(1f)).Subscribe(_ =>
        {
            TransitionManager.Instance.LoadSceneAdditive(GameScenes.Mission);
        });
        informationButton.OnClickAsObservable().ThrottleFirst(TimeSpan.FromSeconds(1f)).Subscribe(_ =>
        {
        });
    }
}
