using System.Collections.Generic;
using UnityEngine;

public class BulkOrderCharacter : MonoBehaviour
{
    [SerializeField] private List<Sprite> normalIconList;
    [SerializeField] private List<Sprite> thanksIconList;

    public Sprite GetNormalIcon(int index)
    {
        return normalIconList[index];
    }
    
    public Sprite GetThanksIcon(int index)
    {
        return thanksIconList[index];
    }

    public int GetRandomIndex()
    {
        return Random.Range(0, normalIconList.Count);
    }
}
