using System;
using UniRx;
using UnityEngine;
using UnityEngine.UI;

namespace MyGame.Scenes.marketing.Scripts
{
    public class ShopCustomizeView : MonoBehaviour
    {
        [SerializeField] private Text levelText;
        [SerializeField] private Button closeButton;
        [SerializeField] private Button infoButton;

        public IObservable<Unit> OnCloseObservable => closeButton.OnClickAsObservable().TakeUntilDestroy(this);
        public IObservable<Unit> OnClickInfoObservable => infoButton.OnClickAsObservable().TakeUntilDestroy(this);

        public void SetLevel(int value)
        {
            levelText.text = $"Lv.{value}";
        }
    }
}