using System;
using UnityEngine;

public class MarketPopcornView : MonoBehaviour
{
    [SerializeField] private SpriteRenderer popcornRenderer;
    [SerializeField] private Sprite caramelSprite;
    private Sprite defaultSkin;

    private void Awake()
    {
        defaultSkin = popcornRenderer.sprite;
    }

    public void ChangeSkin(int flavor)
    {
        if (flavor == 2)
        {
            popcornRenderer.sprite = caramelSprite;
        }
        else
        {
            popcornRenderer.sprite = defaultSkin;
        }
    }
}
