using System;
using System.Collections;
using System.Collections.Generic;
using UniRx;
using UnityEngine;
using UnityEngine.UI;

public class KitchenManager : MonoBehaviour
{
    [SerializeField] private Button cookingButton;
    // Start is called before the first frame update
    void Start()
    {
        cookingButton.OnClickAsObservable().Subscribe(_ => TransitionManager.Instance.LoadScene(GameScenes.Cooking));
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
